import argparse

def parse_args():
    parser = argparse.ArgumentParser(description='STI Inversion problem')
    parser.add_argument('--mode', default='train', choices=['train', 'predict'], help='operation mode: train or predict (default: train)')
    parser.add_argument('--name', type=str, default='_test', help='the name of exp')
    parser.add_argument('--number', type=int, default=6, help='input phase number')
    parser.add_argument('--snr', type=int, default=30, help='phase measurement snr (dB)')
    parser.add_argument('--dataset', default='sti', choices=['sti', 'stieff'], help='dataset to use (default: sti)')
    parser.add_argument('--tesla', default=7, type=float, help='B0 tesla(default: 7)')
    parser.add_argument('--gpu_num', default=1, type=int, choices=[1, 2, 3, 4], help='number of gpu (default: 1)')
    parser.add_argument('--model_arch', default='lpcnn', choices=['vdsrr', 'lpcnn', 'lpcnn_indep', 'neumann', 'lpcnn_unet', 'lpcnn_resunet'], help='network model (default: edsr)')
    parser.add_argument('--iter_num', default=4, type=int, help='network parameter, number of iterations (default: 1)')
    parser.add_argument('--feat_dim', default=64, type=int, help='network parameter, feature dimension (default: 128)')
    parser.add_argument('--num_blocks', default=8, type=int, help='network parameter, number of ResBlocks (default: 16)')
    parser.add_argument('--num_epoch', default=100, type=int, metavar='N', help='number of total epochs to run (default: 20)')
    parser.add_argument('--batch_size', type=int, default=2, help='batch size (default: 4)')
    parser.add_argument('--learning_rate', type=float, default=1e-4, help='learning rate (default: 1e-4)')
    parser.add_argument('--optimizer', default='sgd', choices=['sgd', 'adam', 'sgdadam'], help='optimizer to use (default: adam)')
    parser.add_argument('--momentum', type=float, default=0.9, help='SGD momentum (default: 0.9)')
    parser.add_argument('--no_cuda', action='store_true', default=False, help='disables CUDA training')
    parser.add_argument('--no_save', action='store_true', default=False, help='disables saving tensors')
    parser.add_argument('--resume_file', type=str, default=None, help='the checkpoint file to resume from')
    parser.add_argument('--use_sampler', type=int, default=0, help='use self-defined sampler for multi-resolution dataset. 1: basic two-stream sampler. 2: weighted two-stream sampler.')
    parser.add_argument('--ext_data', type=str, default='', help='external data info (yml)')
    parser.add_argument('--train_list', type=str, default='train_input.txt', help='training data list')
    parser.add_argument('--validate_list', type=str, default='validate_input.txt', help='validation data list')
    parser.add_argument('--test_list', type=str, default='test_input.txt', help='test data list')
    parser.add_argument('--patch_size', type=int, default=64, help='training patch size')
    parser.add_argument('--dk_size', type=int, default=0, help='dipole kernel size')
    parser.add_argument('--samples_per_epoch', type=int, default=2000, help='how many samples per epoch')
    parser.add_argument('--gpu', type=str, default='0', help='set gpu ids (eg: 0,1)')
    parser.add_argument('--train_step_size', type=lambda x: bool(int(x)), default=True, help='whether to learn the step size in proximal gradient descent. If True, step size is trainable; otherwise, fixed. Set by 0/1.')
    parser.add_argument('--is_aug', type=lambda x: bool(int(x)), default=True, help='Apply augmentation to training data? e.g., adding local isotropic lesions, etc')
    parser.add_argument('--random_nori', type=lambda x: bool(int(x)), default=False, help='randomly downsample number of orientations (choose from 1~6) during training')
    
    args = parser.parse_args()
    return args

